name = input("")
cost = int(input(""))
mass = int(input(""))
money = int(input(""))
price_output = str(str(mass) + "кг * " + str(cost) + "руб/кг")
print(f"{'='*16}Чек{'='*16}")
print(f"Товар:{name: >29}")
print(f"Цена:{price_output:>30}")
print(f"Итого:{cost*mass: >26}руб")
print(f"Внесено:{money: >24}руб")
print(f"Сдача:{money-cost*mass: >26}руб")
print(f"{'='*35}")
