name: CI

on:
  push:
  pull_request:

jobs:
  all-subprojects:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install and run all tests
        run: |
          bash scripts/ci_run_all_tests.sh
